services:

  app:
    image: ghcr.io/trinhhoaian-01/travel-planner:latest

    container_name: travel-planner-app

    ports:
      - "8080:80"

    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: ${APP_KEY}

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: travel_planner
      DB_USERNAME: root
      DB_PASSWORD: root@admin

    depends_on:
      mysql:
        condition: service_healthy

    command: >
      sh -c "
        php artisan migrate --force &&
        apache2-foreground
      "

  mysql:
    image: mysql:8.4

    container_name: travel-planner-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root@admin
      MYSQL_DATABASE: travel_planner

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-proot@admin"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: